/*
 * This file was generated by the Gradle 'init' task.
 *
 * The settings file is used to specify which projects to include in your build.
 * For more detailed information on multi-project builds, please refer to https://docs.gradle.org/8.5/userguide/building_swift_projects.html in the Gradle documentation.
 * This project uses @Incubating APIs which are subject to change.
 */

plugins {
    // Apply the foojay-resolver plugin to allow automatic download of JDKs
    id("org.gradle.toolchains.foojay-resolver-convention") version "0.7.0"
}

rootProject.name = "advent-of-code-2024"
include(":utilities")

val excludedDirectoryNames = listOf(
    "build",
    ".git",
    ".gradle",
    "node_modules",
    "buildSrc",
    "gradleSettings",
    ".venv"
)

val rootDirPath = java.nio.file.Path.of(rootDir.path)

// Find all folders in the days directory and include them as projects
file("days").walkTopDown()
    // Avoid visiting files within directories that won't conventionally contain resolvable gradle projects
    .onEnter {
        !excludedDirectoryNames.contains(it.name)
    }
    .filter { it.isFile && it.name == "build.gradle.kts" }
    .map { gradleBuildFile ->
        rootDirPath.relativize(java.nio.file.Path.of(gradleBuildFile.parent)).joinToString("") {
            ":$it"
        }
    }
    .forEach {
        include(it)
    }

includeBuild("build-logic")
