/*
 * This file was generated by the Gradle 'init' task.
 *
 * This project uses @Incubating APIs which are subject to change.
 */

plugins {
    id("advent.of.code.kotlin-library-conventions")
}

dependencies {
    implementation(libs.skrape)
    implementation(libs.guava)
}
